name: CI

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-24.04
    #container: ubuntu:rolling
    steps:
    - uses: actions/checkout@v4
    - name: prereqs
      run: |
        set -eux
        export DEBIAN_FRONTEND=noninteractive
        sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
        sudo apt update
        sudo apt-get build-dep wine -y
        sudo apt install -y sudo git time wget build-essential clang mingw-w64 ccache
    - uses: Trass3r/setup-cpp@master
    - uses: hendrikmuhs/ccache-action@v1
      with:
        verbose: 2
    - name: build
      run: |
        set -ux
        mkdir -p build && cd build
        export CCACHE_STATSLOG=/tmp/stats.log
        ../configure CC="ccache gcc" i386_CC="ccache i686-w64-mingw32-gcc" x86_64_CC="ccache x86_64-w64-mingw32-gcc" \
            CFLAGS="-flto" CROSSCFLAGS="-flto" LDFLAGS="-flto=2" \
            --enable-win64 --disable-tests --with-mingw --enable-archs=i386,x86_64
        time make -j$(($(nproc) + 1)) -k
        make install DESTDIR=../install
        cd ../install/usr/local
        tar cvapf "$GITHUB_WORKSPACE/wine.tar.xz" *
    - uses: actions/upload-artifact@v4
      with:
        name: debug
        path: /tmp/stats.log
    - uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: |
          wine.tar.xz
